name: Memos Build

on:
  push:
      branches:
            - main
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 使用gitea-tool-cache需要指定具体的版本号
        go: ['1.22.4']

    steps:
      - name: Checkout
        uses: https://gitea.cn/actions/checkout@v4
      - name: 安装环境
        uses: kongxiangyiren/gitea-tool-cache@v5
        with:
          # 需要指定具体版本号
          go-version: ${{ matrix.go }}
      - uses: https://gitea.cn/actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go version
    - name: Build for Windows amd64
      run: |
        export GOOS=windows
        export GOARCH=amd64
        # export CC=x86_64-w64-mingw32-gcc
        export CGO_ENABLED=0
        # cd memos
        go build -ldflags="-s -w" -o k5web-windows-amd64.exe server.go
        # x86_64-w64-mingw32-strip k5web-windows-amd64.exe        

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: k5web-binaries
        path: |
          k5web-windows-amd64.exe          
        retention-days: 7
        chunk-size: 10485760 # 10 MB

    # - name: Build for Windows arm64
    #   run: |
    #     export GOOS=windows
    #     export GOARCH=arm64
    #     export CC=aarch64-w64-mingw32-gcc
    #     export CGO_ENABLED=1
    #     cd memos
    #     go build -o memos-windows-arm64.exe ./bin/memos/main.go

    # - name: Build for Linux amd64
    #   run: |
    #     export GOOS=linux
    #     export GOARCH=amd64
    #     export CGO_ENABLED=0
    #     cd memos
    #     go build -o memos-linux-amd64 ./bin/memos/main.go

    # - name: Build for Linux arm64
    #   run: |
    #     export GOOS=linux
    #     export GOARCH=arm64
    #     export CC=aarch64-linux-gnu-gcc
    #     export CGO_ENABLED=1
    #     cd memos
    #     go build -o memos-linux-arm64 ./bin/memos/main.go

    # - name: Build for macOS amd64
    #   run: |
    #     export GOOS=darwin
    #     export GOARCH=amd64
    #     export CGO_ENABLED=0
    #     cd memos
    #     go build -o memos-darwin-amd64 ./bin/memos/main.go

    # - name: Build for macOS arm64
    #   run: |
    #     export GOOS=darwin
    #     export GOARCH=arm64
    #     export CGO_ENABLED=0
    #     cd memos
    #     go build -o memos-darwin-arm64 ./bin/memos/main.go

    # - name: Upload artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: memos-binaries
    #     path: |
    #       memos/memos-windows-amd64.exe
    #       memos/memos-windows-arm64.exe
    #       memos/memos-linux-amd64
    #       memos/memos-linux-arm64
    #       memos/memos-darwin-amd64
    #       memos/memos-darwin-arm64
    #     retention-days: 7
    #     chunk-size: 10485760 # 10 MB